"""initial schema

Revision ID: b40cf5bfd63e
Revises: 
Create Date: 2026-08-25 04:40:04.051422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'b40cf5bfd63e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Meet Elysia lives in its own schema so it can share a Supabase
    # database with the main backend's existing `public` schema
    # without any table-name collisions.
    op.execute("CREATE SCHEMA IF NOT EXISTS elysia")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('companions',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('personality_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('communication_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('background_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interest_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='elysia'
    )
    op.create_index('ix_companions_active', 'companions', ['active'], unique=False, schema='elysia')
    op.create_index('ix_companions_slug', 'companions', ['slug'], unique=True, schema='elysia')
    op.create_table('users',
    sa.Column('external_user_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=35), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_user_id'),
    schema='elysia'
    )
    op.create_index('ix_users_external_user_id', 'users', ['external_user_id'], unique=True, schema='elysia')
    op.create_table('conversations',
    sa.Column('external_conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('companion_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['elysia.companions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['elysia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_conversation_id'),
    schema='elysia'
    )
    op.create_index('ix_conversations_companion_id', 'conversations', ['companion_id'], unique=False, schema='elysia')
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False, schema='elysia')
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False, schema='elysia')
    op.create_table('relationship_context',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('companion_id', sa.UUID(), nullable=False),
    sa.Column('familiarity_level', sa.Enum('new', 'familiar', 'established', name='familiarity_level', native_enum=False), nullable=False),
    sa.Column('preferred_tone', sa.String(length=50), nullable=True),
    sa.Column('conversation_depth', sa.Enum('light', 'medium', 'deep', name='conversation_depth', native_enum=False), nullable=False),
    sa.Column('topic_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interaction_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['elysia.companions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['elysia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'companion_id', name='uq_relationship_context_user_companion'),
    schema='elysia'
    )
    op.create_index('ix_relationship_context_companion_id', 'relationship_context', ['companion_id'], unique=False, schema='elysia')
    op.create_index('ix_relationship_context_user_id', 'relationship_context', ['user_id'], unique=False, schema='elysia')
    op.create_table('ai_events',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('companion_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('companion_version', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['elysia.companions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['elysia.conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['elysia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='elysia'
    )
    op.create_index('ix_ai_events_companion_id', 'ai_events', ['companion_id'], unique=False, schema='elysia')
    op.create_index('ix_ai_events_conversation_id', 'ai_events', ['conversation_id'], unique=False, schema='elysia')
    op.create_index('ix_ai_events_created_at', 'ai_events', ['created_at'], unique=False, schema='elysia')
    op.create_index('ix_ai_events_request_id', 'ai_events', ['request_id'], unique=False, schema='elysia')
    op.create_index('ix_ai_events_user_id', 'ai_events', ['user_id'], unique=False, schema='elysia')
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('companion_version', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['elysia.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='elysia'
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False, schema='elysia')
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False, schema='elysia')
    op.create_table('safety_events',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('input', 'output', name='safety_direction', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['elysia.conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['elysia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='elysia'
    )
    op.create_index('ix_safety_events_conversation_id', 'safety_events', ['conversation_id'], unique=False, schema='elysia')
    op.create_index('ix_safety_events_created_at', 'safety_events', ['created_at'], unique=False, schema='elysia')
    op.create_index('ix_safety_events_request_id', 'safety_events', ['request_id'], unique=False, schema='elysia')
    op.create_index('ix_safety_events_user_id', 'safety_events', ['user_id'], unique=False, schema='elysia')
    op.create_table('memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('companion_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.Enum('preference', 'fact', 'interest', 'goal', 'relationship_context', 'conversation_preference', 'important_event', name='memory_type', native_enum=False), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('privacy_class', sa.String(length=50), nullable=True),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['elysia.companions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['elysia.messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['elysia.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='elysia'
    )
    op.create_index('ix_memories_active', 'memories', ['active'], unique=False, schema='elysia')
    op.create_index('ix_memories_companion_id', 'memories', ['companion_id'], unique=False, schema='elysia')
    op.create_index('ix_memories_user_companion_active', 'memories', ['user_id', 'companion_id', 'active'], unique=False, schema='elysia')
    op.create_index('ix_memories_user_id', 'memories', ['user_id'], unique=False, schema='elysia')

    # Vector similarity index (schema-qualified) — not expressible via
    # the declarative Index() used in the model, so added explicitly
    # here. ivfflat with cosine distance matches OpenAI embedding
    # similarity convention. lists=100 is a reasonable default;
    # revisit as memory volume grows.
    op.execute(
        "CREATE INDEX ix_memories_embedding_cosine ON elysia.memories "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS elysia.ix_memories_embedding_cosine")
    op.drop_index('ix_memories_user_id', table_name='memories', schema='elysia')
    op.drop_index('ix_memories_user_companion_active', table_name='memories', schema='elysia')
    op.drop_index('ix_memories_companion_id', table_name='memories', schema='elysia')
    op.drop_index('ix_memories_active', table_name='memories', schema='elysia')
    op.drop_table('memories', schema='elysia')
    op.drop_index('ix_safety_events_user_id', table_name='safety_events', schema='elysia')
    op.drop_index('ix_safety_events_request_id', table_name='safety_events', schema='elysia')
    op.drop_index('ix_safety_events_created_at', table_name='safety_events', schema='elysia')
    op.drop_index('ix_safety_events_conversation_id', table_name='safety_events', schema='elysia')
    op.drop_table('safety_events', schema='elysia')
    op.drop_index('ix_messages_created_at', table_name='messages', schema='elysia')
    op.drop_index('ix_messages_conversation_id', table_name='messages', schema='elysia')
    op.drop_table('messages', schema='elysia')
    op.drop_index('ix_ai_events_user_id', table_name='ai_events', schema='elysia')
    op.drop_index('ix_ai_events_request_id', table_name='ai_events', schema='elysia')
    op.drop_index('ix_ai_events_created_at', table_name='ai_events', schema='elysia')
    op.drop_index('ix_ai_events_conversation_id', table_name='ai_events', schema='elysia')
    op.drop_index('ix_ai_events_companion_id', table_name='ai_events', schema='elysia')
    op.drop_table('ai_events', schema='elysia')
    op.drop_index('ix_relationship_context_user_id', table_name='relationship_context', schema='elysia')
    op.drop_index('ix_relationship_context_companion_id', table_name='relationship_context', schema='elysia')
    op.drop_table('relationship_context', schema='elysia')
    op.drop_index('ix_conversations_user_id', table_name='conversations', schema='elysia')
    op.drop_index('ix_conversations_created_at', table_name='conversations', schema='elysia')
    op.drop_index('ix_conversations_companion_id', table_name='conversations', schema='elysia')
    op.drop_table('conversations', schema='elysia')
    op.drop_index('ix_users_external_user_id', table_name='users', schema='elysia')
    op.drop_table('users', schema='elysia')
    op.drop_index('ix_companions_slug', table_name='companions', schema='elysia')
    op.drop_index('ix_companions_active', table_name='companions', schema='elysia')
    op.drop_table('companions', schema='elysia')
    # ### end Alembic commands ###