"""add message sequence column for deterministic ordering

Revision ID: 14d5d2b06e4b
Revises: b40cf5bfd63e
Create Date: 2026-08-30 05:12:37.970072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d5d2b06e4b'
down_revision: Union[str, None] = 'b40cf5bfd63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate incorrectly detected ix_memories_embedding_cosine
    # as "removed" — it was created via raw SQL (op.execute) in the
    # initial migration rather than a declarative Index(), so it isn't
    # visible to SQLAlchemy's model metadata for comparison. It is NOT
    # actually being removed; the erroneous drop_index call has been
    # deleted from this migration.
    op.add_column(
        "messages",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        schema="elysia",
    )
    op.create_index(
        "ix_messages_conversation_id_sequence",
        "messages",
        ["conversation_id", "sequence"],
        unique=False,
        schema="elysia",
    )
    op.create_unique_constraint(
        "uq_messages_sequence", "messages", ["sequence"], schema="elysia"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_messages_sequence", "messages", schema="elysia", type_="unique")
    op.drop_index(
        "ix_messages_conversation_id_sequence", table_name="messages", schema="elysia"
    )
    op.drop_column("messages", "sequence", schema="elysia")
    # ### end Alembic commands ###